from Grafo.Grafo import *
import json

grafo = Grafo(False)
# grafo.ingresarN("F")
# grafo.ingresarN("A")
# grafo.ingresarN("F")
# grafo.ingresarN("C")
# grafo.ingresarN("I")
# grafo.ingresarN("O")
# grafo.ingresarN("F")
# grafo.ingresarN("O")
# grafo.ingresarN("P")
# grafo.ingresarA("F", "A", 10)
# grafo.ingresarA("C", "O", 20)
# grafo.ingresarA("F", "C", 10)
# grafo.ingresarA("A", "C", 20)
# grafo.ingresarA("I", "F", 1)
# grafo.imprimirN()
# grafo.imprimirA()
# pozos = grafo.buscarPozos()
# fuentes = grafo.buscarFuentes()
# gradoF = grafo.gradoNodo("F")
# print(pozos)
# print(fuentes)
# print(f"El grado del nodo F es {gradoF}")
# grafo.imrpimirAdyacencia("F")
grafo.cargarGrafoJSON("./Data/planets.json")
print(f"El grafo es {grafo.esConexo()} conexo")
fuentes = grafo.buscarFuentes()
print(fuentes)
pozos = grafo.buscarPozos()
print(pozos)
grafo.boruvka()
# print("--------------------------------------------")
# grafo.kruskal()
# print("--------------------------------------------")
# grafo.caminoMasCorto("Tierra", "Saturno")